In [1]:
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
#importing datasets
data_set= pd.read_csv('50_CompList.csv')
data_set.head(4)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  774031.10
1  162597.70       151377.59        443898.53  California  758873.82
2  153441.51       101145.55        407934.54     Florida  662521.60
3  144372.41       118671.85        383199.62    New York  646243.88

In [3]:
#Extracting Independent and dependent Variable
x= data_set.iloc[:, :-1].values
y= data_set.iloc[:, 4].values

In [4]:
y

array([774031.1 , 758873.82, 662521.6 , 646243.88, 599667.53, 594552.97,
       409530.15, 599705.87, 580874.76, 536995.67, 441668.14, 441207.12,
       471023.57, 480152.39, 532003.58, 498916.68, 464956.72, 522309.05,
       500844.52, 239933.81, 488785.63, 531900.19, 497096.57, 477052.29,
       316899.16, 351180.49, 351514.92, 553155.96, 361845.28, 325775.92,
       268766.  , 312056.53, 219713.72, 373186.25, 414917.66, 331579.1 ,
       356847.79, 291382.51, 271442.62, 296539.9 , 319096.05, 277074.4 ,
       267831.67, 178422.2 , 205318.6 , 125057.2 , 414246.13, 135426.92,
        52285.2 , 161156.86])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Assuming x contains your dataset, and column 4(index 3 in Python) is the categorical feature
# Create a ColumnTransformer to one-hot encode the categorical feature
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [44]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [6]:
#avoiding the dummy variable trap:
x = x[:, 1:]

In [7]:
x

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

In [62]:
# Splitting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)

In [63]:
#Fitting the MLR model to the training set:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [64]:
#Predicting the Test set result;
y_pred= model.predict(x_test)

In [65]:
r_sq = model.score(x_train, y_train)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.9996012834247175


In [21]:
print(f"intercept: {model.intercept_}")

intercept: -3320.8798987708287


In [22]:
print(f"coefficients: {model.coef_}")

coefficients: [-137.64405719  220.56840249    0.98574398    1.01568549    1.00897515]


In [66]:
#Advanced Linear Regression With statsmodels
import numpy as np
import statsmodels.api as sm

In [82]:
x = sm.add_constant(x_train)
x = np.array(x, dtype=float)

In [83]:
x[1,]

array([1.0000000e+00, 1.0000000e+00, 4.6014020e+04, 8.5047440e+04,
       2.0551764e+05])

In [84]:
model = sm.OLS(y_train, x)

In [85]:
results = model.fit()

In [76]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.194e+04
Date:                Thu, 04 Jan 2024   Prob (F-statistic):           6.01e-59
Time:                        18:02:48   Log-Likelihood:                -381.23
No. Observations:                  40   AIC:                             772.5
Df Residuals:                      35   BIC:                             780.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3341.5216   3032.495     -1.102      0.2